export default {
	'/': {
		home: {
			johndiiorio: {
				Documents: {},
				Pictures: {},
				Projects: {
					'Cool-Project.txt': 'Test project',
					'Another cool project.txt': 'Test project 2',
					'A boring terminal project': 'Press return to begin',
					'Tensorflow Project': 'Some random text here',
				},
				'readme.txt': 'README file',
			},
			'lost+found': {},
		},
		usr: {
			bin: {},
			etc: {},
			include: {},
			lib: {},
			lib32: {},
			local: {},
			share: {},
			src: {},
		},
		etc: {},
		dev: {},
		mnt: {},
		proc: {},
		run: {},
		srv: {},
		tmp: {},
		var: {},
		boot: {},
		'lost+found': {},
		opt: {},
		sys: {},
	},
};
